setting:
    sandbox         : false
    security_plugin : 0
    request_log     : false
    sql_log         : false
    timezone        : UTC
    cache_time      : 600
    secret_key      : xxxxxxxxxxxxxxxx
    app_id          :

db_data:
    adapter     : Mysql
    host        : localhost
    port        : 3306
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4

db_trade:
    adapter     : Mysql
    host        : localhost
    port        : 3306
    username    : root
    password    : 123456
    dbname      : test
    charset     : utf8mb4

redis:
    host        : 127.0.0.1
    port        : 6379
    index       : 1
    prefix      : cache_

mq:
    host        :
    port        :
    username    :
    password    :
    vhost       :

sso:
    base_url    : http://www.example.com/api/sso/

api:
  # soap yar http
  rpc_protocol  : yar
  rpc_host      : http://*.rpc.localhost.com